openapi: 3.0.0
info:
  title: Boilerplate Backend
  version: 1.x
  description: |
    Standard Success Response:
    ```
    {
      "message": "ok"
    }
    ```

    Standard Error Response:
    ```
    {
      "error": <message-here>
    }
    ```

servers:
  - url: http://localhost:3030
    description: Local Server

paths:
  /users:
    post:
      tags: ["users"]
      summary: Create User
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSignup"
      responses:
        201:
          description: user created
        400:
          description: username already exists

    put:
      tags: ["users"]
      summary: Update User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        200:
          description: user updated

    delete:
      tags: ["users"]
      summary: Delete User
      responses:
        200:
          description: successful operation

  /users/auth:
    post:
      tags: ["users"]
      summary: Get a login token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"

      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /users/feed:
    get:
      tags: ["users"]
      summary: Get User Feed
      parameters:
        - name: cursor
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      posts:
                        type: array
                        items:
                          $ref: "#/components/schemas/FeedItem"
                        maxItems: 50
                  paging:
                    $ref: "#/components/schemas/PagingData"

  /users/profile/{username}:
    get:
      tags: ["users"]
      summary: Get User Profile
      security: []
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"

  /users/{id}/followers:
    get:
      tags: ["users"]
      summary: Get follower list
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /users/{id}/following:
    get:
      tags: ["users"]
      summary: Get following list
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /posts:
    post:
      tags: ["posts"]
      summary: Create Post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
      responses:
        201:
          description: post created

  /posts/{id}:
    get:
      tags: ["posts"]
      summary: Get Post
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"

        404:
          description: post not found

    delete:
      tags: ["posts"]
      summary: Delete Post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation

  /posts/{id}/likes:
    post:
      tags: ["posts"]
      summary: Add Like to Post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation

    get:
      tags: ["posts"]
      summary: Get Likes for a Post
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: cursor
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      usernames:
                        type: array
                        items:
                          type: string
                  paging:
                    $ref: "#/components/schemas/PagingData"

    delete:
      tags: ["posts"]
      summary: Remove Like from Post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation

components:
  schemas:
    Post:
      type: object
      properties:
        author:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
        likes:
          type: integer
          minimum: 0

    FeedItem:
      type: object
      properties:
        postId:
          type: string
        authorId:
          type: string
        content:
          type: string
        author:
          type: string
        createdAt:
          type: string
          format: date-time

    UserSignup:
      allOf:
        - $ref: "#/components/schemas/UserLogin"
        - type: object
          properties:
            email:
              type: string
          required:
            - email

    UserLogin:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: password
      required:
        - username
        - password

    UserProfile:
      type: object
      properties:
        id:
          type: string
        followers:
          type: number
        following:
          type: number
        createdAt:
          type: string
          format: date-time

    PagingData:
      type: object
      properties:
        cursor:
          oneOf:
            - type: string
            - type: integer
              minimum: 0
        hasMore:
          type: boolean

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
