openapi: 3.0.0
info:
  title: Boilerplate Backend
  version: 1.x

servers:
  - url: http://localhost:3030
    description: Local Server

paths:
  /users:
    post:
      tags: ["users"]
      summary: Create User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: user created
        400:
          description: username already exists

    put:
      tags: ["users"]
      summary: Update User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        200:
          description: user updated

  /posts:
    post:
      tags: ["posts"]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        201:
          description: post created

  /posts/{id}:
    get:
      tags: ["posts"]
      summary: Get Post
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
        400:
          description: post not found

    delete:
      tags: ["posts"]
      summary: Delete Post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation

  /likes/{postId}:
    post:
      tags: ["post"]
      summary: Add Like to Post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        username:
          type: string
        followers:
          type: number
        following:
          type: number
        bookmarks:
          type: array
        passwordHash:
          type: string

    Post:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        author:
          type: string
        likes:
          type: number
        createdAt:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
